export let emailPrefixes = [
  'a',
  'i-dont-understa',
  'on-the-other-ha',
  'in-dema',
  'protected-wetla',
  'a-bit-bla',
  'land-and-expa',
  'pituitary-gla',
  'death-stra',
  'i-cant-sta',
  'aint-it-gra',
  'cobra-comma',
  'ampersa',
  'wayla',
  'fools-erra',
  'were-an-american-ba',
  'inline-spa'
];
